#!/bin/bash

dotfiles=$(echo $0 | xargs dirname)
pushd $dotfiles >/dev/null 2>&1
./requirements/checkreqs git gum
popd >/dev/null 2>&1

git rev-parse >/dev/null 2>&1

if [ $? != 0 ]; then
    echo "$(pwd) is not a git repository. Exiting..."
    exit 1
fi

default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

new_branch() {
    new_branch_name=$(gum input --placeholder "New branch name" --header="$1")
    if git rev-parse --verify ${new_branch_name} >/dev/null 2>&1; then
        new_branch "A branch with name ${new_branch_name} already exists. Please try again."
    else
        [ -n ${new_branch_name} ] && [ "${new_branch_name}" != "" ] && git checkout -b ${new_branch_name}
    fi
}

if [ $(git branch --show-current) = ${default_branch} ]; then
    echo "Warning: Current checked out branch is ${default_branch}, which is most likely protected. Would you rather checkout a new branch based on ${default_branch}?"
    gum confirm "Choose below:" --affirmative="Check out a new branch" --negative="Use ${default_branch}" && new_branch "Please enter a branch name."
fi

select_files_to_add() {
    echo "Pass"
}

add_files() {
    files_with_code=$(git status -s -u)
    if [ ${#files_with_code[@]} = 0]; then
        echo "No files found. Exiting..."
    elif [ ${#files_with_code[@]} = 1]; then
        file_with_code=$(echo "${files_with_code[0]}")
        file=$(echo "${file_with_code}" | cut -c 4-)
        echo "Found one file: $file_with_code"
        gum confirm "Add $file?" && git add ${file} && echo "Added $file"
    else
        echo "Multiple files found. Please pick which files to add."
        select_files_to_add
    fi
}



add_files

# run `git status -s -u` and see if the color can be kept
# if 0 files changed, print warning and exit
# if 1 file changed, gum confirm to commit that one file
# else, gum filter the list and allow multiple selects, then confirm

# if tracking branch set, offer choice between git commit --amend --no-edit + git push -fu origin HEAD
# or just simply adding a new commit

# if no tracking branch set, immediately collect the commit
# then offer to push or force-push
