# ~/.config/shell/completions.zsh
# Tool completions and shell initializations.
# Each block is guarded — safe to source on any machine regardless of what's installed.
# Sourced from ~/.zshrc after oh-my-zsh is initialized.
#
# Note: file-based completions (e.g. _eza, _gh) are generated by
# scripts/install_packages.py into ~/.local/share/zsh/completions/ and
# picked up automatically via the fpath entry in ~/.zshrc.

# ── zoxide — smarter cd (must init after compinit) ────────────────────────────
if command -v zoxide &>/dev/null; then
  eval "$(zoxide init zsh)"
fi

# ── fzf — fuzzy finder key bindings and completions ───────────────────────────
if command -v fzf &>/dev/null; then
  # fzf 0.48+ ships --zsh; fall back to sourcing the completion files directly
  if fzf --zsh &>/dev/null 2>&1; then
    source <(fzf --zsh)
  else
    [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
  fi
fi

# ── gh — GitHub CLI ───────────────────────────────────────────────────────────
# File-based completion is generated by install_packages.py (_gh in fpath).
# The eval approach below is a runtime fallback if the file doesn't exist yet.
if command -v gh &>/dev/null && [[ ! -f "${HOME}/.local/share/zsh/completions/_gh" ]]; then
  eval "$(gh completion -s zsh)"
fi

# ── direnv — per-directory environment variables ──────────────────────────────
if command -v direnv &>/dev/null; then
  eval "$(direnv hook zsh)"
fi
